name: Build & Sign Odfiz APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Libs
        run: npm install
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Capacitor Sync
        run: npx cap sync android

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Manual Sign APK
        run: |
          # 1. Ambil file keystore dari Secrets
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > release.keystore
          
          # 2. Cari lokasi zipalign dan apksigner secara dinamis
          ZIPALIGN=$(find $ANDROID_HOME/build-tools -name zipalign | head -n 1)
          APKSIGNER=$(find $ANDROID_HOME/build-tools -name apksigner | head -n 1)
          
          # 3. Optimasi APK (Zipalign)
          $ZIPALIGN -v 4 android/app/build/outputs/apk/release/app-release-unsigned.apk odfiz-signed.apk
          
          # 4. Tanda tangani (Sign)
          $APKSIGNER sign --ks release.keystore --ks-key-alias "${{ secrets.KEY_ALIAS }}" --ks-pass pass:"${{ secrets.KEYSTORE_PASSWORD }}" --key-pass pass:"${{ secrets.KEY_PASSWORD }}" --out odfiz-final.apk odfiz-signed.apk

      - name: Upload Final APK
        uses: actions/upload-artifact@v4
        with:
          name: Odfiz-Final-APK
          path: odfiz-final.apk
